kind: pipeline
type: docker
name: meeoocat-build

trigger:
  branch:
    - main
  event:
    - push
steps:
  - name: meeoocat-build
    image: docker/compose:1.28.5
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - echo ">>>>>>>>>>> Building ( $CONTAINER_NAME )"
      - echo ">>>>>>>>>>> Build PWD >> $PWD"
      - echo ">>>>>>>>>>> KIINS_COMPOSE_FILE >> $KIINS_COMPOSE_FILE"
      - ls -al
      - ls ./.drone/dev/
      - hostname
      - docker-compose --version
      - docker-compose -f $KIINS_COMPOSE_FILE --profile $CONTAINER_NAME build
      - docker-compose -f $KIINS_COMPOSE_FILE --profile $CONTAINER_WEB_NAME build
  - name: meeocat-deploy-web
    image: docker/compose:1.28.5
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - echo ">>>>>>>>>>> Deploying ( $CONTAINER_WEB_NAME )"
      - echo ">>>>>>>>>>> Deploy PWD >> $PWD"
      - ls -al
      - hostname
      - docker-compose -f $KIINS_COMPOSE_FILE --profile $CONTAINER_WEB_NAME down
      - docker-compose -f $KIINS_COMPOSE_FILE --profile $CONTAINER_WEB_NAME up -d
  - name: meeocat-deploy-api
    image: docker/compose:1.28.5
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - echo ">>>>>>>>>>> Deploying ( $CONTAINER_NAME )"
      - echo ">>>>>>>>>>> Deploy PWD >> $PWD"
      - ls -al
      - hostname
      #- docker-compose -f $KIINS_COMPOSE_FILE --profile $CONTAINER_NAME down --remove-orphans
      - docker-compose -f $KIINS_COMPOSE_FILE --profile $CONTAINER_NAME up -d
environment:
  CONTAINER_NAME: meeoocat-new-api
  CONTAINER_WEB_NAME: meeoocat-web
  KIINS_COMPOSE_FILE: ./.drone/dev/docker-compose.yml

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

#volumes:
#  - name: meeoocat_docs
#    host:
#      path: /usr/src/app/docs