kind: pipeline
type: docker
name: meeoocat-api-build

trigger:
  branch:
    - main
  event:
    - push
steps:
  - name: meeoocat-api-build
    image: docker/compose:1.28.5
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - echo ">>>>>>>>>>> Building ( $CONTAINER_NAME )"
      - echo ">>>>>>>>>>> Build PWD >> $PWD"
      - echo ">>>>>>>>>>> KIINS_COMPOSE_FILE >> $KIINS_COMPOSE_FILE"
      - ls -al
      - ls ./.drone/dev/
      - hostname
      - docker-compose -f $KIINS_COMPOSE_FILE --profile $CONTAINER_NAME build
  - name: dev-meeocat-api-deploy
    image: docker/compose:1.28.5
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - echo ">>>>>>>>>>> Deploying ( $CONTAINER_NAME )"
      - echo ">>>>>>>>>>> Deploy PWD >> $PWD"
      - ls -al
      - hostname
      - docker-compose -f $KIINS_COMPOSE_FILE --profile $CONTAINER_NAME down
      - docker-compose -f $KIINS_COMPOSE_FILE --profile $CONTAINER_NAME up -d

environment:
  CONTAINER_NAME: meeoocat-api
  KIINS_COMPOSE_FILE: ./.drone/dev/docker-compose.yml

#volumes:
#  - name: meeoocat_docs
#    host:
#      path: /usr/src/app/docs